In [42]:
import pandas as pd

In [43]:
df = pd.DataFrame({
    "Size": ['s', 'xl', 'l', 'm', 's', 'xl', 'xl', 's', 's', 'm', 'l', 'l']
})

In [44]:
df

   Size
0     s
1    xl
2     l
3     m
4     s
5    xl
6    xl
7     s
8     s
9     m
10    l
11    l

# ordinal encoding using SCIKIT-LEARN

In [45]:
from sklearn.preprocessing import OrdinalEncoder

In [46]:
ord_data = [['s' , 'm' , 'l' , 'xl']]

In [47]:
oe = OrdinalEncoder( categories = ord_data)
oe.fit( df[["Size"]] )

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [48]:
df["Size_enc"] = oe.transform( df[["Size"]] )

In [49]:
df

   Size  Size_enc
0     s       0.0
1    xl       3.0
2     l       2.0
3     m       1.0
4     s       0.0
5    xl       3.0
6    xl       3.0
7     s       0.0
8     s       0.0
9     m       1.0
10    l       2.0
11    l       2.0

# ordinal encoding USING MAP CODING

In [54]:
ord_data_1 = { 's' : 0 , 'm' : 1 , 'l' : 2 , 'xl' : 3 }

In [55]:
df["Size_enc_map"] = df["Size"].map(ord_data_1)

In [56]:
df

   Size  Size_enc  Size_enc_map
0     s       0.0             0
1    xl       3.0             3
2     l       2.0             2
3     m       1.0             1
4     s       0.0             0
5    xl       3.0             3
6    xl       3.0             3
7     s       0.0             0
8     s       0.0             0
9     m       1.0             1
10    l       2.0             2
11    l       2.0             2

performing ordinal encoding on column PROPERTY_AREA in loan.csv

In [68]:
data = pd.read_csv("loan.csv")

In [69]:
data.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [70]:
data["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [71]:
data['Property_Area'].fillna( data['Property_Area'].mode()[0] , inplace = True)

/tmp/ipykernel_1988/40408617.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Property_Area'].fillna( data['Property_Area'].mode()[0] , inplace = True)

In [72]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [87]:
ord_data_1=[["Rural" , "Semiurban" , "Urban"]]

In [84]:
from sklearn.preprocessing import OrdinalEncoder

In [88]:
oe1 = OrdinalEncoder(
    categories = ord_data_1
)

In [89]:
oe1.fit(data[["Property_Area"]])

OrdinalEncoder(categories=[['Rural', 'Semiurban', 'Urban']])

In [92]:
data["Property_Area"] = oe1.transform(data[["Property_Area"]])

In [93]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2.0,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0.0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2.0,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2.0,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,0.0,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,0.0,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,2.0,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,2.0,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,1.0,N