In [1]:
import pandas as pd

In [8]:
my_dict = {
    "name": ['a', 'b', 'c', 'd', 'a', 'c'],
    "english": [9, 5, 6, 8, 9, 6],
    "hindi": [8, 7, 8, 6, 8, 5]
}

In [9]:
data = pd.DataFrame(my_dict)

In [10]:
data

  name  english  hindi
0    a        9      8
1    b        5      7
2    c        6      8
3    d        8      6
4    a        9      8
5    c        6      5

In [11]:
data.duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [16]:
# to delete the duplicated data
data.drop_duplicates(inplace = True)

In [17]:
data

  name  english  hindi
0    a        9      8
1    b        5      7
2    c        6      8
3    d        8      6
5    c        6      5

In [18]:
# removing duplicated from a dataset
dataset = pd.read_csv("loan.csv")

In [23]:
dataset.duplicated().sum()

np.int64(0)

In [24]:
dataset.shape

(614, 13)

In [26]:
dataset.drop_duplicates(inplace = True)

In [27]:
dataset.shape

(614, 13)